name: Build and Upload Binary

on:
  push:
    tags:
      - 'v*'  # Only run when you push a tag like v1.0.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build release binary
        run: cargo build --release

      - name: Strip binary (optional, to reduce size)
        run: strip target/release/comfy

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/comfy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
